# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180213_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='cat', max_length=100),
            preserve_default=False,
        ),
    ]
